services:
  - type: web
    name: telegram-bot-hosting
    runtime: node
    repo: https://github.com/SIZINGIZ/telegram-bot-hosting
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
